---
title: "ANA 515 Assignment 1"
author: "Ritesh Tikhade"
date: '2021'
output:
  html_document: 
  theme:
    bootswatch: cerulean
---
```{r settings, include=FALSE}
#Install.packages("tidyverse", version="1.0.0", repos ="https://r4ds.had.co.nz/r-markdown.html")
# install.packages("knitr")
# install.packages("bslib")
# install.packages("dplyr")

remove.packages(tidyverse, lib=NULL)

library(tidyverse)
library(knitr)
library(bslib)
library(dplyr)
```

```{r,include=FALSE}

library(tidyverse)
file<- 'https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv'
gun_deaths<- read.csv(file)
```

```{r setup, include=FALSE}
   youth<- filter(gun_deaths,age<= 65)
   Summary(youth)

```

We have data about `r nrow(gun_deaths)` individuals killed by guns. Only `r nrow(gun_deaths) - nrow(youth)` are older than 65.


```{r youth-dist, echo=FALSE}
youth %%
  ggplotaes(age) + geom_freqpoly(binwith=1)
```
#Gun death by race.


```{r youth-dist, echo=FALSE}
youth %%
  ggplotaes(age(fct_infreq(race)%%> fct_rev()))+
  geom_bar() + coord_flip() +
  labs(x = "Victim race")
```


